---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: mysticrenji/flaskapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "256Mi"
          #   limits:
          #      cpu: "100m"
          #      memory: "256Mi"